[package]
name = "segfault_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rhai = "1.16.3"
thiserror = "1.0.56"
clap = { version = "4.4.18", features = ["derive"] }

